// projects/react/todolist/src/app/todolist/form/form.jsx
/*
|--------------------------------------------------------------------------
| FOrm - Component
|--------------------------------------------------------------------------
*/

// Import

import React, { Component } from 'react' 
import { withRouter } from 'react-router-dom';
import {TodoService} from '../../services/todo';
import Task from '../../models/todo.js';


// Todo Component

class Form extends Component {

    constructor(props){
        super(props)

        this.state = {
            newTask: new Task(),
            id:this.props.match.params.id
        }

        this.todoService = new TodoService()
        this.save = this.save.bind(this)

        if(this.state.id){
            this.getData(this.state.id)
        }

    }

    save(event){
        event.preventDefault();

        const title = this.refs.title.value;
        const description = this.refs.description.value;
        const newTask = new Task(title, description) 

        if(this.state.id){
            this.todoService.update(newTask).then(() => {
                // alert('Editado com sucesso')
            })

        }else{
            this.todoService.insert(newTask).then(() => {
                // alert('Adicionado com sucesso')
            })
        }

        this.props.history.push('/');


    }

    getData(id) {
        this.todoService.find(id).then( item => { 
                this.refs.title.value = item.title
                this.refs.description.value = item.description
        });
  
      }

    // Render Component and Childs

    render() {

        
        return ( 
            <main class="content-sidebar">
            <div className="form">
    
                <div className="page-title">
                    <h1>Add Task</h1> 
                </div>
                <form onSubmit={this.save}>
                    <div className="form-row">
                        <label htmlFor="">Title</label> 
                        <input  type="text" ref="title" placeholder="Title" autoComplete="off" name="title"/>
                        <span className="label-error"></span>
                    </div>
                    <div className="form-row">
                        <label htmlFor="">Description</label>
                        <textarea ref="description"  rows="4" placeholder="Description" name="description" ></textarea>
                        <span className="label-error"></span>
                    </div>
                    <div className="form-row"> 
                        <button className="btn-primary" type="submit">Enviar</button>
                    </div>
                </form>  
            </div>
            </main>
        )
    }
}  

export default withRouter(Form);

// projects/vue/todolist/src/components/form/Form.vue
<!-- FORM -->

<template>
  <div class="form">
    
          <div class="page-title">
           <h1>Add Task</h1>
          </div>
          <form @submit.prevent="save()">
            <div class="form-row">
              <label for="">Title</label>
              <input  v-validate="'required'" v-model="task.title" class="mdl-textfield__input" type="text" id="title" maxlength="30" placeholder="Title" autocomplete="off" name="title">
              <span class="label-error">{{ errors.first('title') }}</span> 
            </div>
            <div class="form-row">
              <label for="">Description</label>
              <textarea v-validate="'required'" v-model="task.description" class="mdl-textfield__input" id="description" maxlength="100" rows="4" placeholder="Description" name="description" ></textarea>
              <span class="label-error">{{ errors.first('description') }}</span>
            </div>
            <div class="form-row">
              <button class="btn-primary" type="submit">Enviar</button>
            </div>
          </form>  
  </div>
</template>

<!-- SCRIPT -->

<script>

import {Database} from '../../services/task';
import Task from '../../models/task.js';

var database = new Database();

export default {

 data() {
    return {
      task: new Task(),
      id: this.$route.params.id
    }
  },
  methods: {

    save() {

      this.$validator.validateAll().then(success =>{
          if (success){
            if(this.id){
              database.update(this.task).then(() => {
                  alert('Editado com sucesso')
                  this.task = new Task()
              })
            }else{
              database.insert(this.task).then(() => {
                  alert('adicionado com sucesso')
                  this.task = new Task()
              })
            }

          }else{
            alert("Preencha os campos corretamente")
          }
       })


      

    },

    getData(id) {

      database.find(id).then( item => {
                 this.task = item  
      });

    }
  },
  created(){
        if(this.id){
          this.getData(this.id)
        }
  }
  
}
</script>

<!-- TEMPLATE -->
<style scoped lang="scss">

 @import './form.scss';

</style>
