// projects/react/todolist/src/app/components/sidebar/sidebar.jsx
/*
|--------------------------------------------------------------------------
| Sidebar - Component
|--------------------------------------------------------------------------
*/

// Import

import React from 'react'
import  './sidebar.scss';
import { Link } from 'react-router-dom';

// Sidebar Component

export default props => (
    <aside>
        <nav>
            <ul>
                <li>
                    <Link to="/">Listar</Link>
                    <Link to="/add">Adicionar</Link>  
                </li> 
            </ul>
        </nav>
    </aside> 
)

// projects/vue/todolist/src/components/sidebar/Sidebar.vue
<template>
    <aside>
        <nav>
            <ul>
                <li v-for="route in routes" :key="route.title">
                    <router-link class="menu-aside-item"  :to="route.path ? route.path : '/'">{{route.title}}</router-link>
                </li> 
            </ul>
        </nav>
    </aside> 
</template>

<script>

import { routes }  from '../../routes/routes';

export default {

    data() {

    return {
      routes: routes.filter(route => route.menu)
    }

  }

    
}
</script>

<style scoped lang="scss"> 

@import "./sidebar";


</style>
