// projects/vue/todolist/src/App.vue
<template>
    <!-- APP -->
    <div class="app">
          <app-header/>
          <app-sidebar/>
          <main class="content-sidebar">
            <router-view></router-view> 
          </main>
    </div>  
</template>


<script>

// Import Components

import Sidebar from './components/sidebar/Sidebar.vue'; 
import Header from './components/header/Header.vue'; 
import Main from './components/main/Main.vue'; 
import Form from './components/form/Form.vue'; 

// Create component

export default  {
  name: 'app',

  components: {
    'app-header': Header,
    'app-sidebar': Sidebar,
    'app-main': Main,
    'app-form': Form,
  }

}
</script>

<style lang="scss">

@import "./assets/sass/style";  
@import "./app";  
 

</style>

// projects/angular/todolist/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
 
} 


<!-- Header -->

<app-header></app-header>

<!-- Sidebar -->

<app-sidebar></app-sidebar>

<!-- List and Form -->

<main class="content-sidebar">
        <router-outlet></router-outlet>
</main>
