// projects/react/todolist/src/app/components/pageheader/pageheader.jsx
/*
|--------------------------------------------------------------------------
| Page Header - Component
|--------------------------------------------------------------------------
*/

// Import

import React, { Component } from 'react'
import  './pageheader.scss';  

// Todo Component
 
export default class PageHeader extends Component {

    constructor(props){
        super(props)
    }

    render() {
    
        return ( 
            <div className="page-title">
                <h1>{this.props.title}</h1>
            </div> 
        )
    }
}

// projects/angular/pokedex/src/app/components/pageheader/pageheader.component.ts
import { Component, OnInit , Input} from '@angular/core';

@Component({
  selector: 'app-pageheader',
  templateUrl: './pageheader.component.html',
  styleUrls: ['./pageheader.component.scss']
})
export class PageheaderComponent implements OnInit {

  @Input() title:string = ""

  constructor() { }

  ngOnInit() {
  }

}

<div class="page-header">
    <h1>{{title}}</h1>
</div>
