// projects/react/todolist/src/app/components/search/search.jsx
/*
|--------------------------------------------------------------------------
| Todo - Component
|--------------------------------------------------------------------------
*/

// Import

import React, { Component } from 'react'
import  './search.scss'; 

// Todo Component
 
export default class TodoSearch extends Component {

    constructor(props){
        super(props)
    }

    render() {
    
        return ( 
            <div className="search-box">
                    <div className="container">
                    
                        <input onChange={this.props.searchEngine} type="search" className="form-field_medium"  placeholder="Pesquisar Tarefas" />
                    </div>
            </div>   
        )
    }


}

// projects/angular/todolist/src/app/components/search/search.component.ts
import { Component, OnInit, Input } from '@angular/core';

@Component({
  selector: 'app-search',
  templateUrl: './search.component.html',
  styleUrls: ['./search.component.scss']
})
export class SearchComponent implements OnInit {

  @Input() searchEngine: Function;
 
  constructor() { }

  ngOnInit() {
  }



}

<div class="search-box">
    <div class="container">
        <span class="search" ><i class="material-icons">search</i></span>
        <input  [(ngModel)]="inputValue" (input)="searchEngine($event)"  type="search" class="form-field_medium"  placeholder="Pesquisar Tarefas" />
    </div>
</div>
