// projects/angular/todolist/src/app/todolist/list/list.component.ts
/*
|--------------------------------------------------------------------------
| Model - Main
|--------------------------------------------------------------------------
*/ 

import { Component, OnInit } from '@angular/core';
import { TodoService } from '../../services/todo.service';

@Component({
  selector: 'app-todo',
  templateUrl: './list.component.html', 
  styleUrls: ['./list.component.scss']
})

export class ListComponent implements OnInit {

  itens; 
  inputValue:string = ""

  constructor( 
    private service: TodoService
  ) {}

  ngOnInit(): any {
    this.deleteData = this.deleteData.bind(this)
    this.checkData = this.checkData.bind(this)

    this.service.start().then( db => {
      this.showPosts(db) 
    }) 
  }

  // List 

  showPosts(db){
      db.findAll().then( itemsList => {
        this.itens = itemsList;
    }); 
  }

  // Delete 

  deleteData(event, itemId){
    event.preventDefault()

    this.service.remove(itemId).then( itemsList => {
        alert(`Tarefa ${itemId} deletada`)
        this.itens = itemsList;
    });

  }

  // Check

  checkData(event, itemId){ 
      event.preventDefault()
      this.service.find(itemId).then( item => {
        (item as any).isChecked = !(item as any).isChecked;
          this.service.update(item).then( itemsList => {
            this.itens = itemsList;
          })
      });

  }

}


      <app-pageheader title="Listar tarefas"></app-pageheader>
      <!-- <app-search [searchEngine]="searchEngine"></app-search> -->

    <div class="search-box">
        <div class="container">
            <input  [(ngModel)]="inputValue"   type="search" class="form-field_medium"  placeholder="Pesquisar Tarefas" />
        </div>
    </div>    

      <div class="list-box">
          <article *ngFor="let item of itens | search: inputValue" >
                
            <div class="card {{item.isChecked ? 'done' : 'open'}} ">
                <div class="card-title"> 
                    <h2> {{item.title}}</h2>
                </div>
                <div class="card-content">
                    {{item.description}} 
                </div>
                <div class="card-actions" > 
                    <app-button [callback]="deleteData" icon="clear" [id]="item.id"></app-button>
                    <a [routerLink]="['/add', item.id]">
                        <app-button [callback]="editData" icon="edit"></app-button> 
                        </a>
                    <app-button [callback]="checkData" [id]="item.id"
                    [icon]="item.isChecked ? 'check_box' : 'check_box_outline_blank'">
                    </app-button>
                </div>  
            </div> 
        </article>
      </div>

// projects/react/todolist/src/app/todolist/list/list.jsx
/*
|--------------------------------------------------------------------------
| Todo - Component
|--------------------------------------------------------------------------
*/

// Import

import React, { Component } from 'react'
import  {TodoService} from '../../services/todo';
 

// Import Components

import PageHeader from '../../components/pageheader/pageheader'
import TodoList from '../todolist'
import TodoSearch from '../../components/search/search'

 
// Todo Component

export default class Todo extends Component {

    constructor(props){
        super(props)

        this.database = new TodoService()
        this.state = { itens: [], searchdata: ''}

        this.startDatabase()

        this.searchEngine = this.searchEngine.bind(this)
        this.deleteData = this.deleteData.bind(this)
        this.check = this.check.bind(this)
    }

    startDatabase() {
        this.database.start().then( db => {
            db.findAll().then( itemsList => {
                this.setState({itens: itemsList}) 
            });
        })
    }

    searchEngine(e){

       let inputValue = e.target.value
       this.setState({ searchdata: inputValue})

    }

    deleteData(itemId){

        if(confirm('Deseja Realmente deletar?')) {
            this.database.remove(itemId).then( itemsList => {
                alert(`Tarefa ${itemId} deletada`)
                this.setState({itens: itemsList})  
            });
         }
      
    }

    check(itemId){
        this.database.find(itemId).then(item => {
            item.isChecked = !item.isChecked;
            this.database.update(item).then(itemsList => {
                this.setState({itens: itemsList})
            })
        })
    }

    // Render Component and Childs
 
    render() {

        return ( 
            <div className="main">
                <PageHeader title="List Task"/> 
                <TodoSearch itens={this.state.itens} searchEngine={this.searchEngine}/>
                <TodoList data={this.state} deleteData={this.deleteData} check={this.check}/>  
            </div>
        )
    }
}
